/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 * This algorithm finds what the first triangle number that has over 100 divisors is and displays it for the user.
 *
 * @author Ken Kohlhof
 * Assignment: Homework09
 */
public class Homework09 {
    public static void main(String[] args){
        int triangleNumber = 0;//Triangle number variable
        int incrementor = 0;//Incrementor for the next triangle number
        int divisors = 0;//Number of divisors that the triangle number has

        //While divisors is less than 101 the loop will continue going
        while(divisors < 101){
            incrementor++;//adds 1 to the incrementor
            triangleNumber+= incrementor;//adds incrementor to the triangle number to get the next triangle number
            divisors = 0;//Resets divisor for the next triangle number.
            for(int j = 1; j <= triangleNumber; j++){//For loop that goes from 1 to the triangle number.
                if(triangleNumber%j == 0){//If remainder is 0 it is a divisor of the triangle number.
                    divisors++;
                }
            }
        }
        //Displays message to the user that tells them the first triangle number that has over 100 divisors.
        System.out.println("The value of the first triangle number to have over 100 divisors is " + triangleNumber);
    }
}
// ToDo 01:  Write an algorithm to solve the following problem
    /*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over one hundred divisors?

    */
